version: "3"

services:
  data-workstation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8888:8888"
    env_file:
      - .env

  supabase-connector:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - .:/app            
    env_file:
      - .env
    depends_on:
      - data-workstation
